server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
